import { CategoryDescriptionEnum } from './enums/category-description.enum';
import { CategoryGroupEnum } from './enums/category-group.enum';
import { CategoryType } from './enums/category-type.enum';
import * as admin from 'firebase-admin';
import { randomUUID } from 'crypto';

const categories = [
  {
    id: randomUUID(),
    description: 'Uber',
    descriptionEnum: CategoryDescriptionEnum.UBER,
    group: CategoryGroupEnum.MOBILITY_BY_APP,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: '99Pop',
    descriptionEnum: CategoryDescriptionEnum['99POP'],
    group: CategoryGroupEnum.MOBILITY_BY_APP,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'BlaBlaCar',
    descriptionEnum: CategoryDescriptionEnum.BLABLACAR,
    group: CategoryGroupEnum.MOBILITY_BY_APP,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Lyft',
    descriptionEnum: CategoryDescriptionEnum.LYFT,
    group: CategoryGroupEnum.MOBILITY_BY_APP,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cabify',
    descriptionEnum: CategoryDescriptionEnum.CABIFY,
    group: CategoryGroupEnum.MOBILITY_BY_APP,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Ônibus',
    descriptionEnum: CategoryDescriptionEnum.BUS,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Metrô',
    descriptionEnum: CategoryDescriptionEnum.SUBWAY,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Trem',
    descriptionEnum: CategoryDescriptionEnum.TRAIN,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Combustível',
    descriptionEnum: CategoryDescriptionEnum.FUEL,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Manutenção Veículo',
    descriptionEnum: CategoryDescriptionEnum.VEHICLE_MAINTENANCE,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pedágios/Estacionamento',
    descriptionEnum: CategoryDescriptionEnum.TOLLS_PARKING,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'iFood',
    descriptionEnum: CategoryDescriptionEnum.IFOOD,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Uber Eats',
    descriptionEnum: CategoryDescriptionEnum.UBER_EATS,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Rappi',
    descriptionEnum: CategoryDescriptionEnum.RAPPI,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'James Delivery',
    descriptionEnum: CategoryDescriptionEnum.JAMES_DELIVERY,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: '99Food',
    descriptionEnum: CategoryDescriptionEnum.NINY_NINE_FOOD,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Zé Delivery',
    descriptionEnum: CategoryDescriptionEnum.ZE_DELIVERY,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pedidos Online',
    descriptionEnum: CategoryDescriptionEnum.ONLINE_FOOD_ORDERS,
    group: CategoryGroupEnum.FOOD_DELIVERY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Restaurante',
    descriptionEnum: CategoryDescriptionEnum.RESTAURANT,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Fast Food',
    descriptionEnum: CategoryDescriptionEnum.FAST_FOOD,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Café/Bistrô',
    descriptionEnum: CategoryDescriptionEnum.CAFE_BISTRO,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Farmácia',
    descriptionEnum: CategoryDescriptionEnum.PHARMACY,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Academia',
    descriptionEnum: CategoryDescriptionEnum.GYM,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Estética',
    descriptionEnum: CategoryDescriptionEnum.BEAUTY,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Suplementos',
    descriptionEnum: CategoryDescriptionEnum.SUPPLEMENTS,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Aluguel Imobiliário',
    descriptionEnum: CategoryDescriptionEnum.RENT,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Taxa Condominial',
    descriptionEnum: CategoryDescriptionEnum.CONDOMINIUM_FEE,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Energia',
    descriptionEnum: CategoryDescriptionEnum.ENERGY,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Água',
    descriptionEnum: CategoryDescriptionEnum.WATER,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Gás',
    descriptionEnum: CategoryDescriptionEnum.GAS,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Internet/TV',
    descriptionEnum: CategoryDescriptionEnum.INTERNET_TV,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Telefone',
    descriptionEnum: CategoryDescriptionEnum.PHONE,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Serviços Domésticos',
    descriptionEnum: CategoryDescriptionEnum.HOME_SERVICES,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Reparo/Manutenção Residencial',
    descriptionEnum: CategoryDescriptionEnum.REPAIR_MAINTENANCE,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Financiamento de Veículo',
    descriptionEnum: CategoryDescriptionEnum.VEHICLE_FINANCING,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Financiamento de Imóvel',
    descriptionEnum: CategoryDescriptionEnum.PROPERTY_FINANCING,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Carta de Crédito de Veículo',
    descriptionEnum: CategoryDescriptionEnum.VEHICLE_CREDIT_LINE,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Carta de Crédito de Imóvel',
    descriptionEnum: CategoryDescriptionEnum.PROPERTY_CREDIT_LINE,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro Auto',
    descriptionEnum: CategoryDescriptionEnum.AUTO_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Plano de Saúde/Seguro Saúde',
    descriptionEnum: CategoryDescriptionEnum.HEALTH_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro de Vida',
    descriptionEnum: CategoryDescriptionEnum.LIFE_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro Residencial',
    descriptionEnum: CategoryDescriptionEnum.HOME_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Vestuário e Acessórios',
    descriptionEnum: CategoryDescriptionEnum.CLOTHING_ACCESSORIES,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Compras Online',
    descriptionEnum: CategoryDescriptionEnum.ONLINE_SHOPPING,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Compras Casa e Decoração',
    descriptionEnum: CategoryDescriptionEnum.HOME_DECOR,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Supermercado',
    descriptionEnum: CategoryDescriptionEnum.SUPERMARKET,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pacotes de Turismo',
    descriptionEnum: CategoryDescriptionEnum.TRAVEL_PACKAGES,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Passagens Aéreas',
    descriptionEnum: CategoryDescriptionEnum.FLIGHT_TICKETS,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Hospedagem',
    descriptionEnum: CategoryDescriptionEnum.ACCOMMODATION,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Passeios',
    descriptionEnum: CategoryDescriptionEnum.TOURS,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Aluguel de Carro',
    descriptionEnum: CategoryDescriptionEnum.CAR_RENTAL,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Mensalidade Escolar',
    descriptionEnum: CategoryDescriptionEnum.SCHOOL_TUITION,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Mensalidade Faculdade',
    descriptionEnum: CategoryDescriptionEnum.COLLEGE_TUITION,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pós-graduação',
    descriptionEnum: CategoryDescriptionEnum.POSTGRADUATE_TUITION,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cursos de Línguas',
    descriptionEnum: CategoryDescriptionEnum.LANGUAGE_COURSES,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cursos Técnicos',
    descriptionEnum: CategoryDescriptionEnum.TECH_COURSES,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cursos Online',
    descriptionEnum: CategoryDescriptionEnum.ONLINE_COURSES,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Certificações',
    descriptionEnum: CategoryDescriptionEnum.CERTIFICATIONS,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Aulas Particulares/Reforço Escolar',
    descriptionEnum: CategoryDescriptionEnum.TUTORING,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Material Escolar',
    descriptionEnum: CategoryDescriptionEnum.SCHOOL_SUPPLIES,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Uniforme Escolar',
    descriptionEnum: CategoryDescriptionEnum.UNIFORM,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Assinaturas Educacionais',
    descriptionEnum: CategoryDescriptionEnum.EDUCATIONAL_SUBSCRIPTIONS,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Transporte Escolar',
    descriptionEnum: CategoryDescriptionEnum.SCHOOL_TRANSPORT,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Presentes e Doações',
    descriptionEnum: CategoryDescriptionEnum.GIFTS_DONATIONS,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Taxas e Impostos',
    descriptionEnum: CategoryDescriptionEnum.TAXES,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Ração/Petiscos',
    descriptionEnum: CategoryDescriptionEnum.PET_FOOD,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Veterinário',
    descriptionEnum: CategoryDescriptionEnum.PET_VETERINARY,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pet Shop',
    descriptionEnum: CategoryDescriptionEnum.PET_SHOP,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Farmácia Vet',
    descriptionEnum: CategoryDescriptionEnum.PHARMACY_VET,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cuidados com Dependentes',
    descriptionEnum: CategoryDescriptionEnum.DEPENDENTS_CARE,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Material de Escritório',
    descriptionEnum: CategoryDescriptionEnum.OFFICE_SUPPLIES,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Coworking',
    descriptionEnum: CategoryDescriptionEnum.COWORKING,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Software Empresarial e Serviços Digitais',
    descriptionEnum: CategoryDescriptionEnum.BUSINESS_SOFTWARE,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Emissão de Notas Fiscais',
    descriptionEnum: CategoryDescriptionEnum.INVOICE_ISSUANCE,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Hardware',
    descriptionEnum: CategoryDescriptionEnum.HARDWARE,
    group: CategoryGroupEnum.TECHNOLOGY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Software e Apps',
    descriptionEnum: CategoryDescriptionEnum.SOFTWARE_APPS,
    group: CategoryGroupEnum.TECHNOLOGY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Consultoria',
    descriptionEnum: CategoryDescriptionEnum.CONSULTING,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Manutenção Técnica',
    descriptionEnum: CategoryDescriptionEnum.TECHNICAL_MAINTENANCE,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Artigos Esportivos e Hobbies',
    descriptionEnum: CategoryDescriptionEnum.SPORTS_HOBBIES,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Assinaturas de Entretenimento',
    descriptionEnum: CategoryDescriptionEnum.ENTERTAINMENT_SUBSCRIPTIONS,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Eventos, Shows e Ingressos',
    descriptionEnum: CategoryDescriptionEnum.EVENTS_SHOWS_TICKETS,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cartão de Crédito',
    descriptionEnum: CategoryDescriptionEnum.CREDIT_CARD_PAYMENT,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Taxas Bancárias',
    descriptionEnum: CategoryDescriptionEnum.BANK_TAXES,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Investimentos',
    descriptionEnum: CategoryDescriptionEnum.INVESTMENT,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Compra de Ativos e Criptomoedas',
    descriptionEnum: CategoryDescriptionEnum.BUYING_ASSETS_AND_CRYPTOCURRENCIES,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Empréstimos',
    descriptionEnum: CategoryDescriptionEnum.LOAN_REPAYMENT,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Consumos Diversos',
    descriptionEnum: CategoryDescriptionEnum.OTHER_EXPENSES,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Salário/Pró-labore',
    descriptionEnum: CategoryDescriptionEnum.SALARY,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Recebimento por Serviço Prestado',
    descriptionEnum: CategoryDescriptionEnum.PROFIT_WITHDRAWAL,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Aluguéis e Rendimentos de Ativos',
    descriptionEnum: CategoryDescriptionEnum.RENT_INCOME,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Rendimentos Financeiros',
    descriptionEnum: CategoryDescriptionEnum.INVESTMENT_INCOME,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Reembolsos e Indenizações',
    descriptionEnum: CategoryDescriptionEnum.REIMBURSEMENTS,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Comissões e Bonificações',
    descriptionEnum: CategoryDescriptionEnum.COMMISSIONS_BONUSES,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Doações e Heranças',
    descriptionEnum: CategoryDescriptionEnum.DONATIONS_INHERITANCE,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Aportes e Financiamentos',
    descriptionEnum: CategoryDescriptionEnum.CAPITAL_CONTRIBUTIONS,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Empréstimos',
    descriptionEnum: CategoryDescriptionEnum.RECEIVE_LOAN,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Receitas de Parcerias e Patrocínios',
    descriptionEnum: CategoryDescriptionEnum.PARTNERSHIP_SPONSOR_INCOME,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Aposentadorias e Pensões',
    descriptionEnum: CategoryDescriptionEnum.PENSIONS,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Cashbacks e Recompensas',
    descriptionEnum: CategoryDescriptionEnum.CASHBACK_REWARDS,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Receitas Diversas',
    descriptionEnum: CategoryDescriptionEnum.OTHER_INCOME,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Padaria',
    descriptionEnum: CategoryDescriptionEnum.BAKERY,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Açougue',
    descriptionEnum: CategoryDescriptionEnum.BUTCHER,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Feira/Hortifruti',
    descriptionEnum: CategoryDescriptionEnum.FARMERS_MARKET,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Bebidas/Adega',
    descriptionEnum: CategoryDescriptionEnum.BEVERAGES_LIQUOR,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Bar/Boteco',
    descriptionEnum: CategoryDescriptionEnum.BAR_PUB,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Sorveteria/Doceria',
    descriptionEnum: CategoryDescriptionEnum.ICE_CREAM_DESSERTS,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Lanchonete',
    descriptionEnum: CategoryDescriptionEnum.SNACK_BAR,
    group: CategoryGroupEnum.FOOD,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'InDrive',
    descriptionEnum: CategoryDescriptionEnum.INDRIVE,
    group: CategoryGroupEnum.MOBILITY_BY_APP,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Táxi',
    descriptionEnum: CategoryDescriptionEnum.TAXI,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Lava-rápido',
    descriptionEnum: CategoryDescriptionEnum.CAR_WASH,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Estacionamento Mensal',
    descriptionEnum: CategoryDescriptionEnum.PARKING_MONTHLY,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Ônibus Rodoviário',
    descriptionEnum: CategoryDescriptionEnum.INTERCITY_BUS,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Barca/Balsa',
    descriptionEnum: CategoryDescriptionEnum.FERRY_BOAT,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Bike/Patinete',
    descriptionEnum: CategoryDescriptionEnum.BIKE_SCOOTER_SHARING,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Recarga Elétrica',
    descriptionEnum: CategoryDescriptionEnum.EV_CHARGING,
    group: CategoryGroupEnum.TRANSPORT,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Consulta Médica',
    descriptionEnum: CategoryDescriptionEnum.MEDICAL_CONSULTATION,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Dentista',
    descriptionEnum: CategoryDescriptionEnum.DENTIST,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Exames/Laboratório',
    descriptionEnum: CategoryDescriptionEnum.LAB_EXAMS,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Terapia/Psicólogo',
    descriptionEnum: CategoryDescriptionEnum.THERAPY,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Hospital/Internação',
    descriptionEnum: CategoryDescriptionEnum.HOSPITAL,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Óculos/Lentes',
    descriptionEnum: CategoryDescriptionEnum.OPTICAL,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Fisioterapia',
    descriptionEnum: CategoryDescriptionEnum.PHYSIOTHERAPY,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Vacinas',
    descriptionEnum: CategoryDescriptionEnum.VACCINES,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cabeleireiro/Barbearia',
    descriptionEnum: CategoryDescriptionEnum.HAIR_BARBER,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Manicure/Pedicure',
    descriptionEnum: CategoryDescriptionEnum.NAILS_MANICURE,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Massagem/Spa',
    descriptionEnum: CategoryDescriptionEnum.MASSAGE_SPA,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Nutricionista',
    descriptionEnum: CategoryDescriptionEnum.NUTRITIONIST,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Terapias Alternativas',
    descriptionEnum: CategoryDescriptionEnum.ALTERNATIVE_THERAPY,
    group: CategoryGroupEnum.HEALTH_AND_WELL_BEING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Produtos de Limpeza',
    descriptionEnum: CategoryDescriptionEnum.HOUSEHOLD_SUPPLIES,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Móveis/Eletrodomésticos',
    descriptionEnum: CategoryDescriptionEnum.FURNITURE_APPLIANCES,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Empregada/Diarista',
    descriptionEnum: CategoryDescriptionEnum.DOMESTIC_WORKER,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Jardinagem',
    descriptionEnum: CategoryDescriptionEnum.GARDENING,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Segurança/Monitoramento',
    descriptionEnum: CategoryDescriptionEnum.HOME_SECURITY,
    group: CategoryGroupEnum.HOUSING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Financiamento Estudantil',
    descriptionEnum: CategoryDescriptionEnum.STUDENT_LOAN,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Crédito Pessoal',
    descriptionEnum: CategoryDescriptionEnum.PERSONAL_LOAN,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Consórcio',
    descriptionEnum: CategoryDescriptionEnum.CONSORTIUM,
    group: CategoryGroupEnum.FINANCING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro Celular/Eletrônicos',
    descriptionEnum: CategoryDescriptionEnum.DEVICE_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro Viagem',
    descriptionEnum: CategoryDescriptionEnum.TRAVEL_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro Pet',
    descriptionEnum: CategoryDescriptionEnum.PET_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Plano Odontológico',
    descriptionEnum: CategoryDescriptionEnum.DENTAL_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Seguro Empresarial',
    descriptionEnum: CategoryDescriptionEnum.BUSINESS_INSURANCE,
    group: CategoryGroupEnum.INSURANCE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Calçados',
    descriptionEnum: CategoryDescriptionEnum.SHOES,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Eletrônicos',
    descriptionEnum: CategoryDescriptionEnum.ELECTRONICS,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Livros/Papelaria',
    descriptionEnum: CategoryDescriptionEnum.BOOKS_STATIONERY,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cosméticos/Perfumaria',
    descriptionEnum: CategoryDescriptionEnum.COSMETICS_PERFUMERY,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Brinquedos',
    descriptionEnum: CategoryDescriptionEnum.TOYS,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Joias/Relógios',
    descriptionEnum: CategoryDescriptionEnum.JEWELRY_WATCHES,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Presentes',
    descriptionEnum: CategoryDescriptionEnum.GIFTS,
    group: CategoryGroupEnum.SHOPPING,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Câmbio/Moeda',
    descriptionEnum: CategoryDescriptionEnum.CURRENCY_EXCHANGE,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Bagagem',
    descriptionEnum: CategoryDescriptionEnum.BAGGAGE,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cruzeiro',
    descriptionEnum: CategoryDescriptionEnum.CRUISE,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Transfer/Traslado',
    descriptionEnum: CategoryDescriptionEnum.TRANSFER_SHUTTLE,
    group: CategoryGroupEnum.TRAVEL_AND_TOURISM,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Banho e Tosa',
    descriptionEnum: CategoryDescriptionEnum.PET_GROOMING,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Hotel/Hospedagem Pet',
    descriptionEnum: CategoryDescriptionEnum.PET_BOARDING,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Adestramento',
    descriptionEnum: CategoryDescriptionEnum.PET_TRAINING,
    group: CategoryGroupEnum.PET_CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pensão Alimentícia',
    descriptionEnum: CategoryDescriptionEnum.CHILD_SUPPORT,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Babá',
    descriptionEnum: CategoryDescriptionEnum.NANNY,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Creche',
    descriptionEnum: CategoryDescriptionEnum.DAYCARE,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cuidador de Idosos',
    descriptionEnum: CategoryDescriptionEnum.ELDERLY_CARE,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Mesada',
    descriptionEnum: CategoryDescriptionEnum.ALLOWANCE_GIVEN,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Fraldas/Itens Infantis',
    descriptionEnum: CategoryDescriptionEnum.CHILD_SUPPLIES,
    group: CategoryGroupEnum.CARE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Livros Didáticos',
    descriptionEnum: CategoryDescriptionEnum.TEXTBOOKS,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Excursão Escolar',
    descriptionEnum: CategoryDescriptionEnum.SCHOOL_TRIP,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Formatura',
    descriptionEnum: CategoryDescriptionEnum.GRADUATION_FEES,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Taxas de Prova/Vestibular',
    descriptionEnum: CategoryDescriptionEnum.EXAM_FEES,
    group: CategoryGroupEnum.EDUCATION_AND_STUDIES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Lavanderia',
    descriptionEnum: CategoryDescriptionEnum.LAUNDRY,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Chaveiro',
    descriptionEnum: CategoryDescriptionEnum.LOCKSMITH,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Costureira/Alfaiate',
    descriptionEnum: CategoryDescriptionEnum.TAILOR_SEWING,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Correios/Sedex',
    descriptionEnum: CategoryDescriptionEnum.POSTAL_COURIER,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Funerária',
    descriptionEnum: CategoryDescriptionEnum.FUNERAL_SERVICES,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Guarda-Móveis',
    descriptionEnum: CategoryDescriptionEnum.STORAGE_RENTAL,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Clube/Associação',
    descriptionEnum: CategoryDescriptionEnum.CLUB_MEMBERSHIP,
    group: CategoryGroupEnum.SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Contador/Contabilidade',
    descriptionEnum: CategoryDescriptionEnum.ACCOUNTING,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Advogado/Jurídico',
    descriptionEnum: CategoryDescriptionEnum.LEGAL_SERVICES,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cartório',
    descriptionEnum: CategoryDescriptionEnum.NOTARY,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Despachante',
    descriptionEnum: CategoryDescriptionEnum.CUSTOMS_BROKER,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Tradução',
    descriptionEnum: CategoryDescriptionEnum.TRANSLATION,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Design/Agência',
    descriptionEnum: CategoryDescriptionEnum.DESIGN_AGENCY,
    group: CategoryGroupEnum.PROFESSIONAL_SERVICES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Matéria-prima/Insumos',
    descriptionEnum: CategoryDescriptionEnum.RAW_MATERIALS,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Estoque/Mercadorias',
    descriptionEnum: CategoryDescriptionEnum.INVENTORY_GOODS,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Embalagens',
    descriptionEnum: CategoryDescriptionEnum.PACKAGING,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Frete/Logística',
    descriptionEnum: CategoryDescriptionEnum.SHIPPING_LOGISTICS,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Taxa de Cartão/Maquininha',
    descriptionEnum: CategoryDescriptionEnum.PAYMENT_PROCESSING_FEES,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Comissões Pagas',
    descriptionEnum: CategoryDescriptionEnum.SALES_COMMISSIONS_PAID,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Marketing/Publicidade',
    descriptionEnum: CategoryDescriptionEnum.MARKETING_ADVERTISING,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Anúncios Online',
    descriptionEnum: CategoryDescriptionEnum.ONLINE_ADS,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Folha de Pagamento',
    descriptionEnum: CategoryDescriptionEnum.PAYROLL,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Pró-labore',
    descriptionEnum: CategoryDescriptionEnum.PRO_LABORE,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Benefícios (VR/VT/VA)',
    descriptionEnum: CategoryDescriptionEnum.EMPLOYEE_BENEFITS,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Aluguel Comercial',
    descriptionEnum: CategoryDescriptionEnum.COMMERCIAL_RENT,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Fornecedores',
    descriptionEnum: CategoryDescriptionEnum.SUPPLIERS,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Equipamentos',
    descriptionEnum: CategoryDescriptionEnum.EQUIPMENT,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Manutenção de Equipamentos',
    descriptionEnum: CategoryDescriptionEnum.EQUIPMENT_MAINTENANCE,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Treinamento de Equipe',
    descriptionEnum: CategoryDescriptionEnum.TEAM_TRAINING,
    group: CategoryGroupEnum.BUSINESS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Previdência Privada',
    descriptionEnum: CategoryDescriptionEnum.PRIVATE_PENSION,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Reserva de Emergência',
    descriptionEnum: CategoryDescriptionEnum.EMERGENCY_FUND,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Ações',
    descriptionEnum: CategoryDescriptionEnum.STOCKS,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Renda Fixa',
    descriptionEnum: CategoryDescriptionEnum.FIXED_INCOME,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Fundos',
    descriptionEnum: CategoryDescriptionEnum.FUNDS,
    group: CategoryGroupEnum.INVESTIMENTS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Hospedagem/Domínio',
    descriptionEnum: CategoryDescriptionEnum.WEB_HOSTING_DOMAIN,
    group: CategoryGroupEnum.TECHNOLOGY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Nuvem/Cloud',
    descriptionEnum: CategoryDescriptionEnum.CLOUD_STORAGE,
    group: CategoryGroupEnum.TECHNOLOGY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Acessórios/Gadgets',
    descriptionEnum: CategoryDescriptionEnum.GADGETS,
    group: CategoryGroupEnum.TECHNOLOGY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Conserto de Eletrônicos',
    descriptionEnum: CategoryDescriptionEnum.TECH_REPAIR,
    group: CategoryGroupEnum.TECHNOLOGY,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Cinema/Teatro',
    descriptionEnum: CategoryDescriptionEnum.CINEMA_THEATER,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Jogos/Games',
    descriptionEnum: CategoryDescriptionEnum.GAMES,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Livros/Música',
    descriptionEnum: CategoryDescriptionEnum.BOOKS_MUSIC,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Vida Noturna/Balada',
    descriptionEnum: CategoryDescriptionEnum.NIGHTLIFE,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Parques/Atrações',
    descriptionEnum: CategoryDescriptionEnum.PARK_ATTRACTIONS,
    group: CategoryGroupEnum.LEISURE,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'IPTU',
    descriptionEnum: CategoryDescriptionEnum.PROPERTY_TAX_IPTU,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'IPVA',
    descriptionEnum: CategoryDescriptionEnum.VEHICLE_TAX_IPVA,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Imposto de Renda',
    descriptionEnum: CategoryDescriptionEnum.INCOME_TAX_IR,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Licenciamento',
    descriptionEnum: CategoryDescriptionEnum.VEHICLE_LICENSING,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Multas de Trânsito',
    descriptionEnum: CategoryDescriptionEnum.TRAFFIC_FINES,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'DAS/Simples Nacional',
    descriptionEnum: CategoryDescriptionEnum.SIMPLES_DAS,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'ISS',
    descriptionEnum: CategoryDescriptionEnum.ISS,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'ICMS',
    descriptionEnum: CategoryDescriptionEnum.ICMS,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'INSS',
    descriptionEnum: CategoryDescriptionEnum.INSS_CONTRIBUTION,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'FGTS',
    descriptionEnum: CategoryDescriptionEnum.FGTS_EMPLOYER,
    group: CategoryGroupEnum.TAXES,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Anuidade do Cartão',
    descriptionEnum: CategoryDescriptionEnum.CARD_ANNUAL_FEE,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'IOF',
    descriptionEnum: CategoryDescriptionEnum.IOF,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Tarifas PIX/TED/DOC',
    descriptionEnum: CategoryDescriptionEnum.TRANSFER_FEES,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Juros Cheque Especial',
    descriptionEnum: CategoryDescriptionEnum.OVERDRAFT_INTEREST,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Tarifa de Conta',
    descriptionEnum: CategoryDescriptionEnum.ACCOUNT_MAINTENANCE,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Juros/Encargos',
    descriptionEnum: CategoryDescriptionEnum.INTEREST_CHARGES,
    group: CategoryGroupEnum.BANK,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Dízimo/Oferta',
    descriptionEnum: CategoryDescriptionEnum.TITHE_OFFERING,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Doação/Caridade',
    descriptionEnum: CategoryDescriptionEnum.CHARITY_DONATION,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Perdas/Roubo',
    descriptionEnum: CategoryDescriptionEnum.LOSSES_THEFT,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Multas Diversas',
    descriptionEnum: CategoryDescriptionEnum.MISC_FINES,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Imprevistos',
    descriptionEnum: CategoryDescriptionEnum.UNEXPECTED,
    group: CategoryGroupEnum.OTHERS,
    type: CategoryType.BILLS,
  },
  {
    id: randomUUID(),
    description: 'Venda de Produtos',
    descriptionEnum: CategoryDescriptionEnum.PRODUCT_SALES,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Prestação de Serviços',
    descriptionEnum: CategoryDescriptionEnum.SERVICE_REVENUE,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Freelance/Bico',
    descriptionEnum: CategoryDescriptionEnum.FREELANCE_INCOME,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: '13º Salário',
    descriptionEnum: CategoryDescriptionEnum.THIRTEENTH_SALARY,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Férias',
    descriptionEnum: CategoryDescriptionEnum.VACATION_PAY,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'PLR/Participação nos Lucros',
    descriptionEnum: CategoryDescriptionEnum.PROFIT_SHARING_PLR,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Restituição de Imposto',
    descriptionEnum: CategoryDescriptionEnum.TAX_REFUND,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Saque FGTS',
    descriptionEnum: CategoryDescriptionEnum.FGTS_WITHDRAWAL,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Venda de Usados',
    descriptionEnum: CategoryDescriptionEnum.USED_GOODS_SALE,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Prêmios/Loteria',
    descriptionEnum: CategoryDescriptionEnum.PRIZES_LOTTERY,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Mesada/Ajuda Recebida',
    descriptionEnum: CategoryDescriptionEnum.ALLOWANCE_RECEIVED,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Benefício do Governo',
    descriptionEnum: CategoryDescriptionEnum.GOVERNMENT_BENEFIT,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
  {
    id: randomUUID(),
    description: 'Adiantamento/Vale',
    descriptionEnum: CategoryDescriptionEnum.ADVANCE_RECEIVED,
    group: CategoryGroupEnum.REVENUES,
    type: CategoryType.RECEIVABLE,
  },
];

export default async function (db: admin.firestore.Firestore) {
  const categoriesRef = db.collection('Category');

  for (const method of categories) {
    await categoriesRef.doc(method.id).set({
      id: method.id,
      description: method.description,
      descriptionEnum: method.descriptionEnum,
      group: method.group,
      type: method.type,
      createdAt: new Date().getTime(),
      updatedAt: null,
    });
    console.log(`Documento criado: ${method.description}`);
    console.log(`Documento criado: ${method.descriptionEnum}`);
  }
}
