version: '3.9'

services:
  ngix:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    container_name: nginx
    environment:
      - PORT=${PORT}
    ports:
      - '80:80'
