FROM node:20

LABEL mainteiner 'Caio Queiroz - App Cartera'

RUN echo 'Criando diretório app no container'

WORKDIR /usr/src/app

RUN echo 'Copiando os arquivos para o container'

COPY ./package.json ./yarn.lock ./tsconfig.json ./firebase.json ./

RUN echo 'Instalando as dependências'

RUN yarn install

COPY . .

CMD ["yarn", "start:dev"]
