export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_DESCRIPTION_ENUM_IMMUTABLE = 'CATEGORY_DESCRIPTION_ENUM_IMMUTABLE',
  CATEGORY_DESCRIPTION_REQUIRED = 'CATEGORY_DESCRIPTION_REQUIRED',
  INVALID_CATEGORY_DESCRIPTION_ENUM = 'INVALID_CATEGORY_DESCRIPTION_ENUM',
  INVALID_CATEGORY_GROUP = 'INVALID_CATEGORY_GROUP',
  INVALID_CATEGORY_TYPE = 'INVALID_CATEGORY_TYPE',

  MONEY_INVALID_NUMBER = 'MONEY_INVALID_NUMBER',
  MONEY_NEGATIVE = 'MONEY_NEGATIVE',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',

  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_EMAIL = 'INVALID_EMAIL',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  TIMEOUT = 'TIMEOUT',
  USER_DISABLED = 'USER_DISABLED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
}
