export const CategoryDescriptionEnum = {
  UBER: 'UBER',
  NINY_NINE: 'NINY_NINE',
  BLABLACAR: 'BLABLACAR',
  LYFT: 'LYFT',
  CABIFY: 'CABIFY',
  '99POP': '99POP',

  BUS: 'BUS',
  SUBWAY: 'SUBWAY',
  TRAIN: 'TRAIN',
  AIRPLANE: 'AIRPLANE',
  FUEL: 'FUEL',
  VEHICLE_MAINTENANCE: 'VEHICLE_MAINTENANCE',
  TOLLS_PARKING: 'TOLLS_PARKING',

  IFOOD: 'IFOOD',
  UBER_EATS: 'UBER_EATS',
  RAPPI: 'RAPPI',
  JAMES_DELIVERY: 'JAMES_DELIVERY',
  NINY_NINE_FOOD: 'NINY_NINE_FOOD',
  ZE_DELIVERY: 'ZE_DELIVERY',
  ONLINE_FOOD_ORDERS: 'ONLINE_FOOD_ORDERS',

  RESTAURANT: 'RESTAURANT',
  FAST_FOOD: 'FAST_FOOD',
  CAFE_BISTRO: 'CAFE_BISTRO',

  PHARMACY: 'PHARMACY',
  GYM: 'GYM',
  BEAUTY: 'BEAUTY',
  SUPPLEMENTS: 'SUPPLEMENTS',

  RENT: 'RENT',
  CONDOMINIUM_FEE: 'CONDOMINIUM_FEE',
  ENERGY: 'ENERGY',
  WATER: 'WATER',
  GAS: 'GAS',
  INTERNET_TV: 'INTERNET_TV',
  PHONE: 'PHONE',
  HOME_SERVICES: 'HOME_SERVICES',
  REPAIR_MAINTENANCE: 'REPAIR_MAINTENANCE',

  VEHICLE_FINANCING: 'VEHICLE_FINANCING',
  PROPERTY_FINANCING: 'PROPERTY_FINANCING',
  VEHICLE_CREDIT_LINE: 'VEHICLE_CREDIT_LINE',
  PROPERTY_CREDIT_LINE: 'PROPERTY_CREDIT_LINE',

  AUTO_INSURANCE: 'AUTO_INSURANCE',
  HEALTH_INSURANCE: 'HEALTH_INSURANCE',
  LIFE_INSURANCE: 'LIFE_INSURANCE',
  HOME_INSURANCE: 'HOME_INSURANCE',

  CLOTHING_ACCESSORIES: 'CLOTHING_ACCESSORIES',
  SUPERMARKET: 'SUPERMARKET',
  ONLINE_SHOPPING: 'ONLINE_SHOPPING',
  HOME_DECOR: 'HOME_DECOR',

  FLIGHT_TICKETS: 'FLIGHT_TICKETS',
  TRAVEL_PACKAGES: 'TRAVEL_PACKAGES',
  ACCOMMODATION: 'ACCOMMODATION',
  TOURS: 'TOURS',
  CAR_RENTAL: 'CAR_RENTAL',

  SCHOOL_TUITION: 'SCHOOL_TUITION',
  COLLEGE_TUITION: 'COLLEGE_TUITION',
  POSTGRADUATE_TUITION: 'POSTGRADUATE_TUITION',
  LANGUAGE_COURSES: 'LANGUAGE_COURSES',
  TECH_COURSES: 'TECH_COURSES',
  ONLINE_COURSES: 'ONLINE_COURSES',
  CERTIFICATIONS: 'CERTIFICATIONS',
  TUTORING: 'TUTORING',

  SCHOOL_SUPPLIES: 'SCHOOL_SUPPLIES',
  UNIFORM: 'UNIFORM',
  EDUCATIONAL_SUBSCRIPTIONS: 'EDUCATIONAL_SUBSCRIPTIONS',

  SCHOOL_TRANSPORT: 'SCHOOL_TRANSPORT',

  GIFTS_DONATIONS: 'GIFTS_DONATIONS',
  TAXES: 'TAXES',

  PET_FOOD: 'PET_FOOD',
  PET_VETERINARY: 'PET_VETERINARY',
  PET_SHOP: 'PET_SHOP',
  PHARMACY_VET: 'PHARMACY_VET',

  DEPENDENTS_CARE: 'DEPENDENTS_CARE',

  OFFICE_SUPPLIES: 'OFFICE_SUPPLIES',
  COWORKING: 'COWORKING',
  BUSINESS_SOFTWARE: 'BUSINESS_SOFTWARE',
  INVOICE_ISSUANCE: 'INVOICE_ISSUANCE',

  HARDWARE: 'HARDWARE',
  SOFTWARE_APPS: 'SOFTWARE_APPS',

  CONSULTING: 'CONSULTING',
  TECHNICAL_MAINTENANCE: 'TECHNICAL_MAINTENANCE',

  SPORTS_HOBBIES: 'SPORTS_HOBBIES',
  EVENTS_SHOWS_TICKETS: 'EVENTS_SHOWS_TICKETS',
  ENTERTAINMENT_SUBSCRIPTIONS: 'ENTERTAINMENT_SUBSCRIPTIONS',

  CREDIT_CARD_PAYMENT: 'CREDIT_CARD_PAYMENT',
  BANK_TAXES: 'BANK_TAXES',

  OTHER_EXPENSES: 'OTHER_EXPENSES',

  INVESTMENT: 'INVESTMENT',
  BUYING_ASSETS_AND_CRYPTOCURRENCIES: 'BUYING_ASSETS_AND_CRYPTOCURRENCIES',

  LOAN_REPAYMENT: 'LOAN_REPAYMENT',

  SALARY: 'SALARY',
  PROFIT_WITHDRAWAL: 'PROFIT_WITHDRAWAL',
  RENT_INCOME: 'RENT_INCOME',
  INVESTMENT_INCOME: 'INVESTMENT_INCOME',
  REIMBURSEMENTS: 'REIMBURSEMENTS',
  COMMISSIONS_BONUSES: 'COMMISSIONS_BONUSES',
  DONATIONS_INHERITANCE: 'DONATIONS_INHERITANCE',
  CAPITAL_CONTRIBUTIONS: 'CAPITAL_CONTRIBUTIONS',
  PARTNERSHIP_SPONSOR_INCOME: 'PARTNERSHIP_SPONSOR_INCOME',
  PENSIONS: 'PENSIONS',
  CASHBACK_REWARDS: 'CASHBACK_REWARDS',
  RECEIVE_LOAN: 'RECEIVE_LOAN',
  OTHER_INCOME: 'OTHER_INCOME',
} as const;
